version: "3.1"

services:
  web:
    #image: "nginx:1.24.0"
    volumes:
      - ./nginx/sites-available:/etc/nginx/templates
      - ./html:/usr/share/nginx/html
    build: .
    ports:
      - "8080:80"
    # uncomment to run in debug mode
    # command: [nginx-debug, '-g', 'daemon off;']
